import {
  Focus,
  Settings2,
  ListTodo,
  FolderSync,
  FilePlus2,
  FileDown,
  FolderPlus,
  FolderOpen,
  FileUp,
  Save,
  FilePenLine,
  Search,
  Presentation,
  Bot,
  Map,
  SunMoon,
} from 'lucide-react'

export const editorCommandDefinitions = [
  {
    id: 'focus',
    label: 'Alternar modo foco',
    description: 'Concentrar no documento. Esc restaura a interface.',
    keywords: 'escrever concentracao foco esconder sidebar',
    icon: Focus,
  },
  {
    id: 'appearance',
    label: 'Preferências de aparência',
    description: 'Ajustar texto, largura, tema e animações.',
    keywords: 'preferencias fonte tamanho largura leitura animacoes',
    icon: Settings2,
  },
  {
    id: 'tasks',
    label: 'Painel de tarefas',
    description: 'Reunir e concluir as checklists das notas.',
    keywords: 'tarefas checklist pendentes concluidas projeto',
    icon: ListTodo,
  },
  {
    id: 'local-folder',
    label: 'Pasta local',
    description:
      'Conectar uma pasta, verificar alterações e salvar arquivos Markdown.',
    keywords: 'sincronizar sincronizacao disco arquivos salvar conectar',
    icon: FolderSync,
  },
  {
    id: 'theme',
    label: 'Alterar tema',
    description: 'Alternar entre tema claro e escuro.',
    keywords: 'aparencia aparência dark light cores',
    icon: SunMoon,
  },
  {
    id: 'pdf',
    label: 'Salvar arquivo aberto em PDF',
    description: 'Abrir a impressão do navegador e escolher Salvar como PDF.',
    keywords: 'exportar imprimir print download',
    icon: FileDown,
  },
  {
    id: 'presentation',
    label: 'Modo apresentação',
    description: 'Apresentar o documento em slides divididos pelos títulos.',
    keywords: 'apresentacao slides tela cheia apresentar',
    icon: Presentation,
  },
  {
    id: 'find',
    label: 'Buscar no documento',
    description: 'Encontrar texto na página aberta.',
    keywords: 'pesquisar localizar find texto',
    icon: Search,
    shortcut: 'Ctrl/Cmd F',
  },
  {
    id: 'new-document',
    label: 'Novo documento',
    description: 'Começar um documento temporário.',
    keywords: 'criar novo arquivo nota pagina',
    icon: FilePlus2,
  },
  {
    id: 'new-folder',
    label: 'Nova pasta',
    description: 'Criar uma pasta no local selecionado.',
    keywords: 'criar diretorio subpasta espaco trabalho',
    icon: FolderPlus,
  },
  {
    id: 'open-folder',
    label: 'Abrir pasta',
    description: 'Abrir os documentos Markdown e PDF de uma pasta.',
    keywords:
      'abrir pasta workspace espaco trabalho diretorio importar markdown pdf',
    icon: FolderOpen,
  },
  {
    id: 'open-file',
    label: 'Abrir documento',
    description: 'Abrir um arquivo Markdown ou PDF.',
    keywords: 'pc disco importar carregar markdown pdf',
    icon: FileUp,
  },
  {
    id: 'save-page',
    label: 'Salvar página',
    description: 'Guardar a página aberta neste navegador.',
    keywords: 'salvar pagina documento arquivo gravar save',
    icon: Save,
    shortcut: 'Ctrl/Cmd S',
  },
  {
    id: 'save-as',
    label: 'Salvar como',
    description: 'Baixar uma cópia Markdown com outro nome.',
    keywords: 'exportar renomear download arquivo',
    icon: FilePenLine,
  },
  {
    id: 'ai',
    label: 'Conta do Codex',
    description: 'Conectar o assistente à sua assinatura do ChatGPT.',
    keywords: 'inteligencia artificial codex chatgpt assinatura conta entrar',
    icon: Bot,
  },
  {
    id: 'minimap',
    label: 'Abrir minimapa',
    description: 'Navegar pelos títulos e seções do documento.',
    keywords: 'minimap minipam mapa indice sumario estrutura navegacao',
    icon: Map,
  },
] as const

export type EditorCommandId = (typeof editorCommandDefinitions)[number]['id']
